spring:
  application:
    name: employees-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/employees_service_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    generate-ddl: true
    open-in-view: false
  cloud:
    stream:
      function:
        definition: registrationProcessor
      bindings:
        registrationProcessor-in-0:
          destination: signup-event
        registrationProcessor-out-0:
          destination: registration-event
  zipkin:
    base-url: http://zipkin:9411
  kafka:
    consumer:
      group-id: commissions-service
eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
server:
  port: 8101
  forward-headers-strategy: framework
feign:
  circuitbreaker:
    enabled: true