spring:
  application:
    name: commissions-service
  data:
    mongodb:
      host: ${MONGO_HOST}
      database: commissions_service_db
      port: 27017
      auto-index-creation: true
  cloud:
    stream:
      function:
        definition: registrationEventConsumer
      bindings:
        registrationEventConsumer-in-0:
          destination: registration-event
  zipkin:
    base-url: http://zipkin:9411
  kafka:
    consumer:
      group-id: commissions-service
eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
server:
  port: 8201
  forward-headers-strategy: framework